language: rust
cache: cargo
dist: xenial
sudo: false
group: beta

# necessary for `travis-cargo coveralls --no-sudo`
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

rust:
  - stable
  - beta
  - nightly

install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install openssl --force; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export LIBRARY_PATH="$LIBRARY_PATH:/usr/local/lib"         ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export OPENSSL_INCLUDE_DIR=`brew --prefix openssl`/include ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export OPENSSL_LIB_DIR=`brew --prefix openssl`/lib         ; fi

  - cargo test
  # - rustdoc --test Readme.md -L target/debug/deps -L target/debug
  - cargo doc --no-deps

notifications:
  email:
    on_success: never

after_success:
  - travis-cargo --only stable doc-upload
  - travis-cargo --only stable coveralls --no-sudo

env:
  global:
    secure:



os:
  - linux
  - osx
