language: rust
cache:
  cargo: true

git:
  depth: 1

if: tag IS blank
script: make $SUITE

matrix:
  include:
    - os: linux
      sudo: required
      env: SUITE=checkall
    - os: linux
      sudo: required
      env: SUITE=cargotest
    - os: osx
      env: SUITE=checkall
    - os: osx
      env: SUITE=cargotest
    - os: linux
      env: SUITE=format-check
      install: rustup component add rustfmt-preview
