skip_tags: true

cache:
  - 'target -> appveyor.yml'
  - '%USERPROFILE%\.cargo'

environment:
  fast_finish: true
  DIST_DIR: '.'

  matrix:
    - channel: stable
      target: i686-pc-windows-msvc
    - channel: stable
      target: x86_64-pc-windows-msvc

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV

build: false

test_script:
  - make test
