[package]
name = "sentry"
version = "0.2.0"
authors = ["Sentry <hello@sentry.io>"]
license = "Apache-2.0"
readme = "Readme.md"
repository = "https://github.com/getsentry/sentry-rust"
homepage = "https://github.com/getsentry/sentry-rust"
documentation = "https://github.com/getsentry/sentry-rust"
description = """
Sentry (getsentry.com) client for rust ;)
"""

[features]
default-features = ["with_failure", "with_log"]
with_failure = ["failure"]
with_log = ["log"]

[dependencies]
backtrace = "0.3"
url = "1.7"
failure = { version = "0.1", optional = true }
log = { version = "0.4", optional = true }
futures = "0.1"
serde = "1.0"
serde_json = "1.0"
sentry-types = "0.1.1"
reqwest = "0.8.5"
uuid = { version = "0.6.2", features = ["v4"] }
lazy_static = "1.0.0"

[patch.crates-io]
sentry-types = { path = "../rust-sentry-types" }
