[package]
name = "sentry"
version = "0.3.0-beta"
authors = ["Sentry <hello@sentry.io>"]
license = "Apache-2.0"
readme = "Readme.md"
repository = "https://github.com/getsentry/sentry-rust"
homepage = "https://github.com/getsentry/sentry-rust"
documentation = "https://github.com/getsentry/sentry-rust"
description = """
Sentry (getsentry.com) client for rust ;)
"""
build = "build.rs"

[package.metadata.docs.rs]
all-features = true

[features]
default = ["with_client_implementation", "with_panic", "with_failure", "with_log", "with_device_info", "with_rust_info", "with_debug_meta"]
with_client_implementation = ["reqwest", "im", "url", "backtrace"]
with_panic = []
with_failure = ["failure", "regex"]
with_log = ["log"]
with_error_chain = ["error-chain"]
with_device_info = ["libc", "hostname", "uname"]
with_rust_info = ["rustc_version"]
with_debug_meta = ["findshlibs"]
with_shim_api = []

[dependencies]
backtrace = { version = "0.3", optional = true }
url = { version = "1.7", optional = true }
failure = { version = "0.1", optional = true }
log = { version = "0.4", optional = true }
serde = "1.0"
serde_json = "1.0"
sentry-types = "0.3.0"
reqwest = { version = "0.8.5", optional = true }
uuid = { version = "0.6.2", features = ["v4"] }
lazy_static = "1.0.0"
regex = { version = "0.2.10", optional = true }
error-chain = { version = "0.11.0", optional = true }
im = { version = "10.0.0", optional = true }
libc = { version = "0.2.40", optional = true }
hostname = { version = "0.1.4", optional = true }
uname = { version = "0.1.1", optional = true }
findshlibs = { git = "https://github.com/gimli-rs/findshlibs", rev = "b47a834e7ce3d07ef6dc6fba5ea89d5d6e615848", optional = true }

[build-dependencies]
rustc_version = { version = "0.2.2", optional = true }

[dev-dependencies]
failure_derive = "0.1.1"
pretty_env_logger = "0.2.2"
