[package]
name = "sentry"
version = "0.1.2"
authors = ["Alexis Agahi <aagahi@prefetch.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/aagahi/rust-sentry"
homepage = "https://github.com/aagahi/rust-sentry"
documentation = "https://github.com/aagahi/rust-sentry"
description = """
Sentry (getsentry.com) Service for rust ;)
"""


[dependencies]
hyper = "0.9.5"
time = "0.1.35"
chrono = "0.2.22"
